version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: key-{{ checksum "project/build.properties" }}-{{ checksum "build.sbt" }}
      - run: sbt test:compile
      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.sbt
          key: key-{{ checksum "project/build.properties" }}-{{ checksum "build.sbt" }}
      - run: sbt test
      - store_test_results:
          path: target/test-reports/
